# Generated by Django 3.0.6 on 2020-06-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msg', '0006_auto_20200603_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstatus', models.CharField(max_length=500)),
                ('txnid', models.CharField(max_length=64)),
                ('txnamount', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_txnid', models.CharField(max_length=50)),
                ('tdate', models.CharField(max_length=100)),
                ('msg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='msg.Message')),
            ],
        ),
    ]
