# Generated by Django 3.0.6 on 2020-06-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0002_auto_20200604_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
