# Generated by Django 3.0.6 on 2020-06-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='counter',
        ),
    ]
