# Generated by Django 3.0.6 on 2020-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0004_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cust_id',
            field=models.CharField(default='CUST_2gjsdk', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='order_id',
            field=models.CharField(default='ORDER_2gjsdk', max_length=15),
            preserve_default=False,
        ),
    ]
