# Generated by Django 3.0.6 on 2020-06-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_auto_20200603_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
